# Generated by Django 3.2.1 on 2021-05-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfkb',
            name='testFkC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdc_test.testfkc'),
        ),
    ]
