# Generated by Django 3.2.1 on 2021-05-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_test', '0002_alter_testfkb_testfkc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testo2ob',
            name='TestO2oC',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdc_test.testo2oc'),
        ),
    ]
