# Generated by Django 3.2.1 on 2021-05-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_test', '0002_testrelaya_testrelayb'),
        ('gdc_test', '0003_alter_testo2ob_testo2oc'),
    ]

    operations = [
    ]
