# Generated by Django 3.2 on 2021-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_test', '0006_auto_20210528_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
