# Generated by Django 3.2 on 2022-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_test', '0007_auto_20210528_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
